# docker-compose.yml


services:
  mysql:
    image: mysql:8.0
    container_name: airflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Zaq12wsx.
      MYSQL_DATABASE: cripto_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: Zaq12wsx.
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    environment:
      -  AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://root:Zaq12wsx.@mysql:3306/cripto_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy

  scheduler:
    build: .
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://root:Zaq12wsx.@mysql:3306/cripto_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: scheduler
    depends_on:
      mysql:
        condition: service_healthy
      webserver:
        condition: service_healthy

volumes:
  mysql_data: